spring.application.name=gestion-guias-despacho
server.port=8080

spring.datasource.url=jdbc:h2:mem:guiasdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true

app.efs.path=${EFS_PATH:/tmp/guias-despacho}
app.aws.region=${AWS_REGION:us-east-1}
app.s3.bucket=${S3_BUCKET:guias-despacho-demo}
app.s3.enabled=${S3_ENABLED:false}
